config/routes.rb
Bookmark::Application.routes.draw do

	devise_for :users, :skip => [:sessions]
	as :user do
		get 'signin' => 'welcome#index', :as => :new_user_session
		post 'signin' => 'devise/sessions#create', :as => :user_session
		delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
	end
	
	resources :user_bookmarks do
		collection do
			post 'multi_detroy' => 'user_bookmarks#multi_destroy', :as => :multi_destroy
		end
	end
	
	post "youtube" => "youtube#get_info", :as => :youtube
	
  get "welcome/index"

	root :to => 'welcome#index'	
	

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :user_bookmarks

  devise :database_authenticatable, :registerable, :rememberable
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/user_bookmark.rb
# project name is Bookmark so model name set to UserBookmark (avoid ambigius)
class UserBookmark < ActiveRecord::Base
	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  #overriding devise default redirect
  def after_sign_in_path_for(resource)
		user_bookmarks_path
	end
end

app/controllers/user_bookmarks_controller.rb
class UserBookmarksController < ApplicationController
	before_filter :authenticate_user!
	
	def index
		@bookmark = UserBookmark.new
		@bookmarks = current_user.user_bookmarks.all
	end
	
	def create
		@bookmark = current_user.user_bookmarks.new(params[:user_bookmark])
		if @bookmark.save
			redirect_to root_path, notice: 'Bookmark was successfully created.'
		else # actualy no reason for a link to fails, cause no validations
			redirect_to root_path, notice: 'You have an error.'
		end
	end
	
	def destroy
		@bookmark = current_user.user_bookmarks.find(params[:id])
		@bookmark.delete		
		redirect_to user_bookmarks_path, :notice => 'Bookmark was succesfully deleted !' 
	end
	
	def multi_destroy
		@count = 0
		delete_list = params[:delete].keys
		delete_list.each do |id| 
			current_user.user_bookmarks.find(id).delete
			@count += 1		
		end
		@book_work = "Bookmark was"
		@book_work = "Bookmarks were" unless @count == 1
		flash[:bookmarks] = "#{@count} #{@book_work} succesfully deleted."
		redirect_to user_bookmarks_path
	end
	
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	if current_user
  		redirect_to user_bookmarks_path
		end
  end
end

app/controllers/youtube_controller.rb
require 'rexml/document'
require 'cgi'
require 'open-uri'

class YoutubeController < ApplicationController

	def get_info
		client = YouTubeIt::Client.new
		@video = client.video_by(params[:video_id])
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/user_bookmarks_helper.rb
module UserBookmarksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/youtube_helper.rb
module YoutubeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookmark</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= flash[:notice] %>
<% if current_user %>
	<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>    
	<h1>Welcome <%= current_user.email %>!</h1>
<% else %>
	<h1>Welcome To the Bookmark App!</h1>
<% end %>
<%= yield %>

</body>
</html>

app/views/user_bookmarks/_bookmark_form.html.erb
<%= form_for(@bookmark) do |f| %>
  <div class="field">
    <%= f.label :link, "Please enter a link to be saved:" %><br />
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <%= f.submit "Save link to bookmarks list" %>
  </div>
<% end %>

app/views/user_bookmarks/_bookmarks_list.html.erb
<h2> List of all your bookmark </h2>
<%= form_tag(multi_destroy_user_bookmarks_path, :method => "post") do %>
<table>
  <tr>
    <th>Mark</th>
    <th>Link</th>
    <th></th>
  </tr>
<p> <%= flash[:bookmarks] %> </p>
	<% @bookmarks.each do |bookmark| %>
		<% abs_link = bookmark.link %>
		<% abs_link = "http://" + bookmark.link unless bookmark.link.match(/(http|https):\/\//) %>
		<tr>
			<td><%= check_box_tag("delete[#{bookmark.id}]",bookmark.id) %></td>
		  <td><%= link_to bookmark.link, abs_link, :target => "_blank"
 %></td>
		  <td><%= link_to 'Delete', user_bookmark_path(bookmark.id), :confirm => 'Are you sure?', :method => :delete %></td>
		</tr>
	<% end %>
</table>

	<br />
  <%= submit_tag("Delete Selected", :confirm => 'Are you sure?') %>
<% end %>
<br /> 

app/views/user_bookmarks/_youtube.html.erb
<%= form_tag youtube_path,:id => 'youtube_check', :remote => true do |f| %>
  <% hidden_field_tag 'video_id' %>
<% end %>

<div class='youtube'>
</div>

app/views/user_bookmarks/index.html.erb
<%= render 'bookmark_form' %>

<%= render 'youtube' %>

<% if @bookmarks.empty? %>
	</br >
	<%= flash[:bookmarks] %>
	<h2> You dont have any bookmarks.</h2>
<% else %>
	<%= render 'bookmarks_list' %>
<% end %>

app/views/welcome/index.html.erb
<h2> Please login to the app: </h2>
<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
	<div><%= f.label :email %><br />
	<%= f.email_field :email %></div>

	<div><%= f.label :password %><br />
	<%= f.password_field :password %></div>

	<% if devise_mapping.rememberable? -%>
	  <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
	<% end -%>

	<div><%= f.submit "Sign in" %></div>
<% end %>
<p> <%= flash[:alert] %> </p>
<p> not registered yet ? <%= link_to('Register', new_user_registration_path)  %> </p>

app/views/youtube/get_info.js.erb
$(".youtube").html("<h2> Youtube Information: </h2>");
$(".youtube").append("<div id='movie-title'><%= escape_javascript(@video.title) %></div>");
$(".youtube").append("<img src=<%= escape_javascript(@video.thumbnails[0].url) %> />");